### ISSUE TITLE
Active Camera2D shifts GUT test window

### ISSUE THREAD

**Issue by Xrayez** [bitwes/Gut#121]
**Version: 6.7.0, 6.8.0**

Active Camera2D shifts GUT test window making it partially invisible, depending on camera alignment and position:

![window_shifted_by_camera](https://user-images.githubusercontent.com/17108460/59104318-f51d7380-8939-11e9-835c-c1175ed39ee5.png)

**Reproduction steps:**
1. Instance a test scene with `Camera2D` as child and make it `current`.
2. Add this scene as child in any test method.

**Comment by Xrayez** [comment]
The GUT window should probably be instanced on a separate `CanvasLayer` to avoid the main canvas transform to affect GUT test window position, but perhaps `VisualServer` methods could be used directly to fix this without affecting the existing `GutScene` node structure.

**Comment by Ajver** [comment]
@Xrayez I always remove any child that I add to Gut while running tests (i.e. in `after_each` method). It helps me to keep memory clean and avoid that type of issues (anyway, that's still a bug).

But even if I remove any child I had the same issue today and I realized it happens when I doubled the scene with an active camera and added it as a child.

**Comment by Xrayez** [comment]
@Ajver yeah I typically go for scene-based approach for integration tests at least, so that's where the camera interferes with the GUT when it's used for debugging purposes outside of GUT.

And I recently stumbled upon this feature: godotengine/godot#27742, which removes the need to add such debug cameras within test scenes.

But it's still a bug nonetheless.

**Comment by bitwes** [comment]
Well, I finally got around to this one.  I've prototyped an approach that I think will work.

* Add an option to run tests in a viewport
* Instead of adding tests as children of the GUT instance, they will be added to the viewport.
* Add the following options:
  * run_in_viewport
  * viewport_size
  * screen_size

When running in the viewport, the viewport will be sized to the default screen resolution in Project Settings.  You can override the Project Settings resolution with `screen_size` so that you have screen space where GUT and the viewport do not overlap.  You can also set the viewport size.  The viewport will always be right justified.

This might become the default behavior if it doesn't cause any bugs.  I can't think of any and GUT doesn't care (so far).  Let me know if anything comes to mind.

**Comment by bitwes** [comment]
Fixed in next release.  See PR #344 for details.
