### ISSUE TITLE
Am I testing this right?

### ISSUE THREAD

**Issue by jhamges** [bitwes/Gut#125]
I'm pretty new to TDD so I won't be surprised if the answer to this is "yeah you just don't know what you're doing" but here it goes.

The code I'm trying to test is part of my "Collectable" scene, and I'm trying to test that when a certain input is handled, then a certain function is called. I saw that assert_called is only available via doubles, though. I already feel like I'm kinda making this hacky because what I gleaned from Butch's "TTD and Pong" videos is that you only really use doubles when you're simulating another object so that you can test what you actually want to test (e.g. doubling the ball in the wall test).

Anyway, here's the code for "Collectable.gd":
```
extends Area2D

var _this_item = null

func _input(event):
	if event.is_action_pressed("collect"):
		collect_item(_this_item)
		
func collect_item(node):
	if not _this_item:
		return
	emit_signal("collected", node)
	update_item()
	node.queue_free()

...
```

and then the test I'm attempting to make:

```
extends 'res://addons/gut/test.gd'

var PlayerCollect = load('res://Collectable.gd')

func test_collectable_input_is_collect():
	var pca = double(PlayerCollect).new()
	var input = InputEventKey.new()
	input.set_scancode(KEY_C)
	InputMap.add_action("collect")
	InputMap.action_add_event("collect", input)
	input.set_pressed(true)
	
	pca._input(input)
	
	assert_called(pca, 'collect_item')
```

Here you can see I'm setting up the InputMap and key press. But when running the test it fails, saying it expected collect_item to have been called, and it says only _init() and _input() were called.

What am I doing wrong here? Am I still missing something in setting up the input? Or should I not even be testing the _input() method, and just testing my own custom methods like collect_item()? I still feel like there's value in testing what happens via certain inputs but maybe I'm wrong.

Any help is appreciated!

**Comment by bitwes** [comment]
I think you need to use partial_double instead of double.  It will give u
and object that retains all of its functionality but you can still spy on
it.

Check the wiki on partial doubles.  They are brand new in the latest
release 6.8.0 (btw last time I tried to install gut from asset library it
still had the old version so u may have to install from GitHub).

Doubles have their functionality removed.  So your _input method doesn't do
anything.  It just reports back to gut that it was called.  Partial doubles
will report back to gut and do whatever they originally did.  You can also
stub partial doubles methods to skip their original functionality.

Optionally with a normal double, you can stub _input to "to_call_super"
which will make _input do normal stuff and the rest of the methods will
still do nothing.

**Comment by jhamges** [comment]
Thanks Butch! Upgrading to 6.8.0 and using partial doubles made it work! I'll go ahead and close this - thanks for making Gut and providing all of this information (including the tutorials).

**Comment by jhamges** [comment]
Going to reopen this since I've just got another "am i doing this right" question.

My World scene has a Timer on it that spawns energy on timeout:

```
# World.gd 

onready var Energy = preload('res://energy/Energy.tscn')

func _on_Spawner_timeout():
	var energy = Energy.instance()
	add_child(energy)
```

and the test:

```
extends 'res://addons/gut/test.gd'

var World = load('res://World.tscn')

func test_on_Spawner_timeout():
	var w = World.instance()
	add_child(w)

	w._on_Spawner_timeout()

	assert_not_null(w.get_node("Energy"))
```

Which works, but **should I really be using the scene file to test this**? Doesn't that make it more of an implementation test than a unit test? I tried using the World.gd file to test this but I couldn't figure it out. Is there a way to do it with that?

**Comment by bitwes** [comment]
Sorry for the late reply.  Saw this and forgot to get back to it.

You're on the right track, you shouldn't be testing the timeout method directly.  This is almost an integration test.  There's two approaches you can take.  In this case I'd use the 2nd approach but I'll put them both out there since the first could be useful.

The first approach is to get the timer object in your test, make it emit the timeout signal and then verify that whatever the timeout was supposed to do happened.  Note I removed `add_child` for this one since you don't need it here.
```
func test_on_Spawner_timeout():
	var w = World.instance()
	w.get_spawn_timer().emit_signal('timeout') # have to write a get_spawn_timer or ref timer directly

	assert_not_null(w.get_node("Energy"))
```
The second approach uses Godot's `yield` and Gut's `yield_for`.  This will make Gut pause and wait x seconds giving the timer time to timeout.  You need to `add_child` on this one or the timer won't start b/c it isn't in the tree.
```
func test_on_Spawner_timeout():
	var w = World.instance()
	add_child(w)
	w.do_something_that_would_kick_off_timer()
	yield(yield_for(<timer_timeout_time> + 1), YIELD)

	assert_not_null(w.get_node("Energy"))
	w.queue_free() # you'll build up a bunch of worlds if you don't do this at the end of the test.
```
Check out the yield section of the wiki for more info on yielding and tests.

**Comment by bitwes** [comment]
closing this, if you have any other questions you can re-open or make a new issue.
