### ISSUE TITLE
make the Gut.tscn scene scroll down smoothly like a terminal

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#159]
Hey, I'd like to the PR for this,

this would be great I think because when you have a lot of outputs, it can become tedious to click with your mouse to scroll down

so I thought I would make it so 
*when you click arrow down it scroll downs slowly
*when you press 'd' for down (or 'u' for up) it would fall (rise) a little less than half a screen, like a man page for instance
Any idea thoughts? its an open question

**Comment by bitwes** [comment]
If you would like command-line like controls, have you tried running from the command line?  https://github.com/bitwes/Gut/wiki/Command-Line.  

If you have tried the command line and still prefer running the scene then I could see this being useful.  You can use page-up/down and home/end keys now but you have to make the area selectable using the button above the "continue" button.

Under the covers the scene uses a TextEdit control which GUT doesn't allow you to disable.  When running tests on a phone/tablet this gets really annoying because touching anywhere in the control makes the keyboard come up (even though it is read only).  To combat this, there is an invisible control over top of the TextEdit so that you can't directly click on the TextEdit, but you CAN click on its scrollbar.

Try making it selectable first and see if you have enough keyboard options (it seemed a little finicky).  The easy fix might be to expose the option to make it selectable in the Inspector.

If binding new keys still seems better then we should bind:
* the arrow keys to go up/down slowly
* page-up/page-down to work like they do now when selectable
* can bind other keys but do so in a way that would make changing these bindings easy for the end user.  Nothing worse than not being able to remap shortcuts.

**Comment by bitwes** [comment]
In the next release (7.0.0) I've switched the control in the gui to a RichTextLabel and it has all this great functionality.  The arrows and pgup/pgdwn work as expected.  If you would still like to see some key mapping I'd ask you open a new issue.  I'll close this one out when 7.0.0 goes live.

**Comment by bitwes** [comment]
Implemented in 7.0.0.
