### ISSUE TITLE
Continue button hidden behind sprites / unable to continue

### ISSUE THREAD

**Issue by shrnjad** [bitwes/Gut#165]
First of all, thank you so much for this plugin! 🙏

When adding graphics assets during test setup with `add_child()` the GUT UI is hidden behind the (full-screen) UI I am testing. If I use `pause_before_teardown()` the GUT continue button will not be visible and I am stuck unable to continue.

What is the best practice to handle this situation? I would not mind the GUT UI being on top of the scene.

**Comment by bitwes** [comment]
Thank you, it's great to hear that and I love seeing people use it!

I've not come up with an elegant solution to this yet.  I've thought of a couple approaches but nothing good yet.  In general `pause_before_teardown` calls shouldn't remain in your tests.  I created it so that you could see what everything looked like at the end of your test in case it wasn't acting the way you expected it to.  Once you got the test to pass correctly you would remove them.  

You can ignore ALL pauses or (and this is the best I've come up with so far) or you can lower the opacity of GUT to see stuff behind it.  Then, when using `add_child(...)` set `show_behind_parent` .  Another approach is to use `get_tree().root.add_child(...)` instead.  GUT will still be in the way in a little in both cased but you should be able to see enough of your scene.  If you use `get_tree().root.add_child(...)` then GUT won't move the items if you try to drag GUT out of the way.

I knew I'd forget to remove some or I'd want to keep a few calls around for awhile so I added functionality to ignore all pauses.  I added this to the command line tool since that would be the most likely place that you would want to ignore them.  You can get the same effect though if you add the following to the scene that has GUT in it.
```
func _ready():
  gut.set_ignore_pause_before_teardown(true)
```

Hope that helps.  Let me know if you have anymore questions, if not go ahead and close down the issue.  Thanks for using GUT!

**Comment by shrnjad** [comment]
It is a great plugin and really helpful!

It compares well to Unit and UI Testing I have been using in Xcode, which is quite good. Maybe in the long run, we could add some kind of UI / gameplay testing convenience to GUT.

Your comments are also immensely helpful, I am closing the issue now!
