### ISSUE TITLE
Assertion for dictionary contents

### ISSUE THREAD

**Issue by hilfazer** [bitwes/Gut#177]
I know of no way to compare dictionary contents without writing a loop. By contents i mean same keys and same values associated with those keys.
I need something that will compare following dictionaries equal:
```
 {1:2, 3:4}
 {3:4, 1:2}
```

There's a hash() function but it apparently cares about order of elements which, afaik, is an implementation detail.

`{1:2, 3:4}.hash() == {3:4, 1:2}.hash() # returns False`

Being able to compare dictionaries' contents with a single line would be great.

**Comment by bitwes** [comment]
It looks like `str` sorts the keys.  For simple dictionaries comparing the str conversion could be a workaround.  You'd have to know your data pretty well to trust this though.  Notice that it sees `1` and `'1'` as equal since just the string representation of both is being compared.  
```
var d1 = {1:2, 3:4}
var d2 = {3:4, 1:2}
var d3 = {1:2, 3:4}
var d4 = {'3':4, '1':2}

print(d1, d2, d3, d4)
print(str(d1) == str(d2))
print(str(d2) == str(d3))
print(str(d1) == str(d4))

# prints 
{1:2, 3:4}{1:2, 3:4}{1:2, 3:4}{1:2, 3:4}
True
True
True
```
A recursive version of something like this could do the trick.  You won't get to see the differences but you will know they aren't equal.
```
func sort_dict(dict):
	var sorted = {}
	var dict_keys = dict.keys()
	dict_keys.sort()

	for i in range(dict_keys.size()):
		sorted[dict_keys[i]] = dict[dict_keys[i]]

	return sorted

func compare_dict(d1, d2):
	var d1_sorted = sort_dict(d1)
	var d2_sorted = sort_dict(d2)

	return d1_sorted.hash() == d2_sorted.hash()
...
print('sorted compare ', compare_dict({1:2, 3:4}, {3:4, 1:2})) # prints True
```
