### ISSUE TITLE
Should not compare floats to strings.

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#182]
The various asserts should not support comparing strings to floats.  There are issues with the string conversion that will prevent a lot of numbers from being exactly equal.  There's been a failing test for awhile in the GUT tests.  I found the following bug that explains the issue:  godotengine/godot/#27706

The following fails for 0.92, 1.92, 1.9 but 1 and 1.5 pass
``` python
# found in test/unit/test_test.gd
var _float_vals = [['0.92', 0.92], ['1', 1.0], ['1.5', 1.5], ['1.92', 1.92], ['1.9', 1.9]]
func test_passes_when_cast_char_to_float(vals=use_parameters(_float_vals)):
	var sval = vals[0]
	var fval = vals[1]
	
	assert_eq(float(sval), fval, 'float(string)')
	assert_eq(sval.to_float(), fval, '.to_float()')
```
The following asserts will have to be addressed.
* assert_eq(got, expected, text=""):
* assert_ne(got, not_expected, text=""):
* assert_almost_eq(got, expected, error_interval, text=''):
* assert_almost_ne(got, not_expected, error_interval, text=''):
* assert_gt(got, expected, text=""):
* assert_lt(got, expected, text=""):
* assert_between(got, expect_low, expect_high, text=""):

**Comment by short-story-long** [comment]
Hej, I've looked into the implementation of `assert_eq` a little bit and as far as I can see the function internally calls `_do_datatypes_match__fail_if_not`. So it already checks if the values for `got` and `expected` have the same type. Exception only is made for `int / float` comparison. Therefore, if developers want to compare values of different types they'll have to do the cast before calling `assert_eq`. This isn't something the assert functions can prevent developers to do, I guess. 

As far as I understand the discussion in the referenced godot-engine bug, the issue lies within the different possibilities to represent a float value. The godot community therefore suggests to define an error tolerance `epsilon` and check if the difference between `got` and `expected` is within `epsilon`.

The following example might fail:
```
func test_fails_float_comparison() -> void:
	var value = 1 / 0.11
	var compare_to = 9.090909
	assert_eq(value, compare_to)
```
Whereas this example passes:
```
func test_passes_float_comparison() -> void:
	var value = 1 / 0.11
	var compare_to = 9.090909
	var epsilon = 0.000001

	if abs(value - compare_to) < epsilon:
		assert_true(true)
	else:
		assert_true(false, str(value) + " not equal " + str(compare_to))
```

On the other hand, the second code snipped is specific to float comparisons. We cannot use this with strings or complex types, at least not if they don't have the `-` operator implemented. Here we may want to have something like this:
```
func test_passes_string_comparison() -> void:
	var value = str(1 / 0.11)
	var compare_to = str(9.090909)
	
	var result = value.casecmp_to(compare_to)
	if result == 0:
		assert_true(true)
	else:
		assert_true(false, str(value) + " not equal " + str(compare_to) + ", result: " + str(result))


func test_passes_obj_comparison() -> void:
	var value = str(1 / 0.11)
	var compare_to = str(9.090909)
	var method_name = 'special_compare_to'
	var result = -1
	if value.has_method(method_name):
		result = value.call(method_name, "compare_to", compare_to)
	if result == 0:
		assert_true(true)
	else:
		assert_true(false, str(value) + " not equal " + str(compare_to) + ", result: " + str(result))
```

My proposal would be to encapsulate the specific compare logic and extract it from the `assert_eq` (...and later maybe other asserts as well). The `assert_eq` then calls a specific comparison routine depending on the type of `expected`. So it will do something like this:
- try to cast `got` into type of `expected`
  -  if this fails, the test fails, ideally with some error message
- call sub-routine with the type specific comparison logic
  - if the compare is successful the test passes
  - else the test fails

Maybe in the future we can give developers the opportunity to hand in their own comparison routine, if they have complex objects they wish to compare with each other. (But this is out of scope for this issue... )

**Comment by bitwes** [comment]
I think the way to do this would be, if a comparison of two `floats` fails then it converts them both to strings and compares them.  If they are equal then the test would still fail but the message would be altered to inform the user that they might be comparing  a float  generated from a string and a normal float.

**Comment by bitwes** [comment]
As mentioned, Gut is doing the right thing and doesn't allow comparing strings and floats.  The failing tests were casting floats to strings and vice versa.  This won't work and is pretty hard to detect.  Unless this comes up again this issue will be closed.  I've removed the tests that were failing appropriately.
