### ISSUE TITLE
Many failures == freeze a godot

### ISSUE THREAD

**Issue by allkhor** [bitwes/Gut#20]
Look at the example:

```
func test_loop_failure():
	for hour in range(0, 25):
		for minute in range(0, 60):
			for second in range(0, 60):
				var time = hour+minute+second
				var wrong = 1
				assert_eq(time, wrong)
```
This test has never end, or time is catastrophically big to awaiting result.
Possible fix:
```
func _fail(text):
	_summary.asserts += 1
	_summary.failed += 1
	if _summary.failed < 1000:
		if(_current_test != null):
			_current_test.passed = false
		p('FAILED:  ' + text, LOG_LEVEL_FAIL_ONLY)
		if(_current_test != null):
			p('  at line ' + str(_current_test.line_number), LOG_LEVEL_FAIL_ONLY)
	elif _summary.failed == 1000:
		p("Too many failures, please check your tests")
	_update_controls()
	end_yielded_test() 
```
Thanks for your work!

**Comment by bitwes** [comment]
I got pretty quick results with the following:

```
extends "res://addons/gut/test.gd"

func test_2000_failures():
	for i in range(2000):
		assert_true(false)
		
func test_4000_failures():
	for i in range(4000):
		assert_true(false)
		
func test_6000_failures():
	for i in range(6000):
		assert_true(false)
```
Since Godot doesn't have a way to raise an exception, there's no clean way to stop the current test from running.  It would be possible to stop more tests from running, but having two of these cases seems unlikely.  We could try to limit the output for a given test but there are very few cases where you should be making multiple assertions per test so I don't think this is that much of an issue.  Chances are you'll get tired of waiting and fix the test.

**Comment by bitwes** [comment]
Usually, what I do when I have to run something a large number of times I'll count the number of times it went right or wrong and make an assertion at the end making sure it acted the way I thought it would.  That way you get one failure instead of 1000.
