### ISSUE TITLE
Gut scene min size is 740.

### ISSUE THREAD

**Issue by Ramh5** [bitwes/Gut#205]
My game is for mobile so I have a width of 720. However it is not possible to resize the Gut node below 740 wide. This might not be an issue related to Gut itself and maybe there is a simple solution for my problem by using Godot properly but I was not able to find it. I tried to temporarily set width of my game using `ProjectSettings.set_setting("display/window/size/width", 1000)` but it does not seem to have any effect. Does anyone else have this issue and how did you solve it?

**Comment by bitwes** [comment]
You could try setting the scale of the GUT control.  In 6.8.x setting the scale in the scene should work.  In 7.0.0 It is broke but you can do it with the following code:
```
# This code assumes you have a node in your tree named "Gut" and you've connected
# the gut_ready signal to this method.
func _on_Gut_gut_ready():
	$Gut.get_gut().get_gui().rect_scale = Vector2(.5, .5)
```

**Comment by Ramh5** [comment]
It does work with this workaround, unfortunately the font does not scale down nicely.  I really wished I could do that instead
`ProjectSettings.set_setting("display/window/size/width", 1000)` to just launch this scene in a bigger window than the default projects preset but there must be something I don't  understand about how Godot works. 

Anyway I appreciate the work you are doing. I know nothing about how to do Unit testing in general but I like the concept and I am starting to be tired of checking dozens of stuff every time I refactor parts of my game. I will try to learn it. You can close this issue at your convenience.

**Comment by short-story-long** [comment]
Hej, I ran into the same issue with the prototype I'm working on right now. It is mobile game as well and therefore the orientation is portrait not landscape. 

While developing / testing you can do the following: in the project settings > Display > Window in the `size` settings you can define a `test_width` and `hest_height`. Here you can set the `test_width=740`. In the `stretch` settings change aspect to `aspect=expand`. This allows you to resize the window when testing with gut and you can see the parts that are invisible otherwise.

In the long run I'd like to make a proposal for a resizable gui. But it is not a good first issue, therefore I want to get myself familiar with the project first :)

**Comment by bitwes** [comment]
FYI, you can resize the GUI to be bigger, just not smaller.  The layout gets complicated when the width gets too small.  You can resize at runtime by grabbing the bottom right corner.
