### ISSUE TITLE
Painful absence of existing ways to throw you (and contributors) some love for your amazing work <3

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#241]
Hey,
I don't contribute to this repo because it already fits my needs (i have a policy of helping by fixing my needs in projects when they don't fulfil it yet)
But i do use it and love it.

I think OSCommunity can be a pretty negative place, so for every sparkle of love lit in my heart when i use Gut and love doing so, I'd like to be able to just tell you so (I'm a very emotionnal person).

That's it, thanks, you random internet person

**Comment by bitwes** [comment]
Thank you!  This made my day.

**Comment by bitwes** [comment]
I kept trying to think of a way to make this absence less painful and never got back to just say thank you for saying thank you.  I might just pin a "Thank You" issue...that's the best approach I've come up with so far.  It seems self serving to make one myself though.  So...since any good issue has some amount  of back and forth, I request your help in creating this "Thank You" issue.  A title of "Thank You" and a simple "thank you" in the body or "hey, you asked for this so here it is" will work.

If you would like a "code review" for this post then post any drafts here.

Thanks for your thanks fell random internet person.

**Comment by astrale-sharp** [comment]
Hmm good thinking ;)
its funny to think that posting this issue was my individual solve for the issue (very meta), but I'm going to allow others in by following your advice,
lets have this new thank you issue open until they shut internet down then ~~~

**Comment by bitwes** [comment]
#256 fills the void.  Thanks everyone for using  GUT!
