### ISSUE TITLE
using gut to test another addon in developpment is tricky

### ISSUE THREAD

**Issue by astrale-sharp** [bitwes/Gut#260]
Hey there, im working on [a gdnative addon](https://github.com/MatejSloboda/Dijkstra_map_for_Godot/issues/90) and im using gut to help me out.
I realized i had to move all the addon code to the addons folder but gut is already there and that would be quite confusing for the user
So i moved gut in a new addon/Tests folder and i changed all the code links looking like "res://addons/gut" to "res://addons/Tests/gut" hoping it would suffice, it did not.
I tried hacking around a little bit but it didnt proved efficient as of yet

we could leave gut where it is, but it would feel better to be able to move it around..
we could put our code in another folder not named addons but then if the user has gut installed, it would overwrite it if they are not careful...

Does anyone have an idea how to integrate gut in addon dev without running into these issues?
Much Love, Ash

**Comment by bitwes** [comment]
I think what you are looking for is the `.gitattributes` file.   I only discovered this file when I needed to exclude test files from a GUT release.  It was a life saver.  You can use this file to exclude paths from the `.zip` file that is generated when you create a release on Github.  You'll have to use this file to make sure that your addon only includes files at `res://addons/<your addon>`.

You should probably add `addons/gut` to your `.gitignore` file too.  I think it is best practice not to include addons into your own repo.  (For a game, it might make sense to  include the plugin since Godot doesn't have a build mechanism to pull in specific dependency versions.)

https://git-scm.com/docs/gitattributes
https://git-scm.com/docs/gitignore
https://github.com/bitwes/Gut/blob/master/.gitattributes

**Comment by astrale-sharp** [comment]
omg yes! this sounds way better than my hacks!
we use gut as a dev dependencies so i think it makes sense to have it in our gut repo? but excluding gut from the asset store with .gitattributes does sound very good i'll try that!

**Comment by bitwes** [comment]
Reopen if you're still having issues.
