### ISSUE TITLE
Question about Spies and Doubles

### ISSUE THREAD

**Issue by Splyth** [bitwes/Gut#276]
In my code I have a function that I want to unit test:

```
func _physics_process(delta: float) -> void:
	calulate_velocity_2d(delta)
	calulate_velocity_3d(delta)
	move_hero()
```

I looked at the documentation and determined that I want to use [assert_called](https://github.com/bitwes/Gut/wiki/Asserts-and-Methods#assert_called) so I've created a double like so (subject is a scene object I created elsewhere):
```
        doubled_subject = double(subject).instance()
```

then I attempt to call it in my test like so:
```
    func test_physics_process():
        doubled_subject._physics_process(delta)
        assert_called(doubled_subject, 'calulate_velocity_2d')
```

But it ONLY registers the initial call to the physics_process and not the functions that it calls within it e.g. (calculate_velocity_2d, calculate_velocity_3d, move_hero, etc)

I did attempt to use the ".and_call_super()" while stubbing it, and every other method i can think of.

I did notice in your "assert_called" that you manually called the functions that you were testing.

So is it possible to register these nested function calls to the doubled object or no?

**Comment by bitwes** [comment]
Adding the stub should have fixed your issue.  Maybe you have things out of order.  Seeing the full test code would help.

I would use a [partial double](https://github.com/bitwes/Gut/wiki/Partial-Doubles) and [simulate](https://github.com/bitwes/Gut/wiki/Simulate) if you only need to spy on the object you are testing.
```gdscript
  func test_physics_process():
        doubled_subject = partial_double(subject).instance()
        simulate(subject, 1, .1)
        assert_called(doubled_subject, 'calulate_velocity_2d')
```

Since it appears you are testing `subject` by itself, a better test would be to check for the results of `calulate_velocity_2d` instead of verifying it was called.  Spying is most  useful when verifying two objects interact the way you expect (without having  to worry about the implementation of the other), not how an object interacts with itself.

Yielding can  also be useful in these scenarios.

https://github.com/bitwes/Gut/wiki/Simulate
https://github.com/bitwes/Gut/wiki/Yielding
https://github.com/bitwes/Gut/wiki/Partial-Doubles

**Comment by Splyth** [comment]
I tried the simulate suggestion but I still just got

```
    [Failed]:  Expected [calulate_velocity_2d] to have been called on [KinematicBody:1660](double of hero.tscn)
    Calls made on [KinematicBody:1660]
      * _physics_process(0.1)
          at line 41
```
So what you're suggesting is don't run any testing on the `__physics_process` function itself but test the other functions it calls?

I know code coverage isn't a thing in godot (at least as far as I know) but that feels like a gap.

I also tried with yielding and got similar results

**Comment by bitwes** [comment]
Using simulate or yield to test how your object performs over time is
better than testing _process or _physics_process directly.  In general you
shouldn't test private methods.  Simulate and yield get around that rule
since you definitely want to test how your object behaves over time in
different scenarios.

I'm not sure why it's not working.  Can you post your test code?

**Comment by Splyth** [comment]
```
extends KinematicBody

const FLOOR_NORMAL = Vector3(0.0, 1.0, 0.0)

export var speed = 7
export var accel = 43
export var friction = 43
export var gravity = 30.0
export var jump_force = 12.0

var velocity_y := 0.0 # Hero's Current Jump Velocity
var velocity_2d = Vector2.ZERO # Speed Hero is Moving on the X,Z Axis
var velocity_3d = Vector3.ZERO # Combines heros 2d Movement and 3D Jump Velocity
var input_vector = Vector2.ZERO # Calcuation of which buttons are being pressed.

onready var hitbox = $bodyslam_hitbox

# Internal: Called every time there is a change in the inputs
#
# event - A InputEvent that contain information about the change that acured.
#
# Example
#	_unhandled_input(InputEvent)
#
# Returns nothing
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("jump"):
		velocity_y = jump_force

	input_vector = Vector2(
		Input.get_action_strength("ui_right") - Input.get_action_strength("ui_left"),
		Input.get_action_strength("ui_down") - Input.get_action_strength("ui_up")
	).normalized()

# Internal: Ran when that engine runs it physics process
#
# delta = length of time since the previous frame
#
# Example
#	_physics_process(0.167)
#
# Returns Nothing
func _physics_process(delta: float) -> void:
	calulate_velocity_2d(delta)
	calulate_velocity_3d(delta)
	move_hero()

# Internal: Called during the physics process to generate a 2d vector based on the movement keys.
#
# delta = length of time since the previous frame
func calulate_velocity_2d(delta: float):
	if input_vector != Vector2.ZERO:
		velocity_2d = velocity_2d.move_toward(input_vector * speed, accel * delta)
		hitbox.knockback_vector = Vector3(input_vector.x, 0, input_vector.y)
	else:
		velocity_2d = velocity_2d.move_toward(Vector2.ZERO, friction * delta)

# Internal: Called during the physics process to generate a 3d vector based on the current 2d vector
#
# delta = length of time since the previous frame
func calulate_velocity_3d(delta:float):
	if not is_on_floor():
		velocity_y -= gravity * delta

	velocity_3d = Vector3(
		velocity_2d.x,
		velocity_y,
		velocity_2d.y
	)

# Internal: Called by the physics process to move the hero according to the global vector3d variable.
func move_hero():
	velocity_3d = move_and_slide(velocity_3d, FLOOR_NORMAL)

	if is_on_floor() or is_on_ceiling():
		velocity_y = 0.0

```

**Comment by bitwes** [comment]
There appears to be some issue with `_physics_process` and doubling.  This kinda rings a bell but I can't remember exactly what the issue is.  I was able to get it to work with `ignore_method_when_doubling`.  I pasted  your code into `res://thing.gd`

``` gdscript
extends 'res://addons/gut/test.gd'

var Thing = load("res://thing.gd")

func test_physics_process():
    # must happen before any double or partial_double are called
    ignore_method_when_doubling(Thing, '_physics_process') 
    var d_thing = partial_double(Thing).new()
    add_child(d_thing)
    simulate(d_thing, 1, .1)
    assert_called(d_thing, 'calulate_velocity_2d')
```

I still don't think this is a great test.  You don't care which methods are called in _physics_process as much as something happens after _physics_process has been called.  Over time the method names could change or be moved.  Verifying a method has been called requires the test to know too much about the implementation.  You should be testing behavior more than implementation.

These would be better tests (I used `Vector2(1, 1)` where you'd have to pick something more meaningful.  I also assumed the addition of `get_velocity_2d`)
``` gdscript
func test_physics_process_updates_velocity_2d_with_zero_vector():
    var thing = autofree(Thing.new())
    thing.input_vector = Vector2.ZERO
    simulate(thing, 1, .1)
    assert_eq(thing.get_velocity_2d(), Vector2(1, 1))

func test_physics_process_updates_velocity_2d_with_input_vector():
    var thing = autofree(Thing.new())
    thing.input_vector = Vector2(1, 1)
    simulate(thing, 1, .1)
    assert_eq(thing.get_velocity_2d(), Vector2(1, 1))
```

**Comment by Splyth** [comment]
Interesting!

I learned how to do unit testing from a medical IT company so it wouldn't surprise me if they taught me that way because they really are that anal in medical devices testing.

I think I'll take your advice and ease off testing the physics_process directly and instead test what the results of that function.

Thanks for taking the time to walk me through this!
