### ISSUE TITLE
Gut in CI - Opening the scene causes error "Make sure resources have been imported by opening the project in the editor at least once."

### ISSUE THREAD

**Issue by StefanLobbenmeier** [bitwes/Gut#301]
Creating this issue since I just had it in my CI and was not able to find an existing issue. I guess the error message is already quite good, but still want to document this.

More complete error message:
```
ERROR: load: Failed to load resource 'res://Spatial.tscn'.
   At: core/io/resource_loader.cpp:212.
ERROR: _load: Failed loading resource: res://Spatial.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282.
SCRIPT ERROR: GDScript::reload: Parse Error: Can't preload resource at path: res://Spatial.tscn
   At: res://test/unit/HumanoidTest.gd:3.
```

I guess for my CI I will attempt to open the project using the Godot command once? But I am a bit unsure how to close it again.

**Comment by StefanLobbenmeier** [comment]
Ok so I tried deleting .import folder on my local machine and then running 

godot -e -q

To start the Godot editor and immediately close it afterwards. But even then the error does not disappear. Any other advice?

**Comment by StefanLobbenmeier** [comment]
Minimal example for reproduction:

Create new project, add GUT, add Test file:

```
extends "res://addons/gut/test.gd"

var MainScene = preload('res://Spatial.tscn').instance() as Node
```

**Comment by StefanLobbenmeier** [comment]
Relevant documentation: https://docs.godotengine.org/en/stable/getting_started/workflow/assets/import_process.html

> Additionally, extra assets will be preset in the hidden res://.import folder:
> If any of the files present in this folder is erased (or the whole folder), the asset or assets will be reimported automatically. As such, committing this folder to the version control system is optional. It can shorten reimporting time when checking out on another computer, but it takes considerably more space and transfer time. Pick your poison!

**Comment by StefanLobbenmeier** [comment]
It looks like the export option generates the .import files as well, running

`godot --export "Linux/X11"`

prints 
`reimport: begin: Importiere Nutzerinhalte erneut steps: 7`

So that is what I am going to add for now I guess

**Comment by StefanLobbenmeier** [comment]
Hmm in the CI environment even the Godot export command fails. I am going to ask in the Godot project now.

**Comment by StefanLobbenmeier** [comment]
I found other people suffering from this as well: https://github.com/godotengine/godot-proposals/issues/1362

**Comment by StefanLobbenmeier** [comment]
I managed to fix this now following this patch: https://github.com/Kersoph/open-sequential-logic-sandbox/pull/4/files

I guess it would be nice to have a scene like that also in Gut, but its not that big of a deal to have it separate. 

This is the command I ended up using in my CI: `timeout 120s godot --editor buildscript/rebuild_and_close/rebuild_and_close.tscn || true`

**Comment by bitwes** [comment]
After reading some of those links, this is a Godot/CI issue and I can't think of a good place to put something like this in GUT.  The workaround is small enough that it probably better off created individually.

Reopen if you have any further thoughts.

**Comment by hsandt** [comment]
I have a similar issues with other assets when I open GUT repo as a Godot project itself (not when I import it into an existing project though - or maybe it's because AssetLib downloads latest stable 9.1.0 but honestly it doesn't differ from latest in godot_4 branch by that much.

So it may be that the issue only occurs on a fresh project open, which would explain why it also occurs on CI. Below I logged all the errors I got on a fresh repo opening (I know add-on is not meant to be opened as a standalone project, but cleaning those issues may eventually help with cleaning CI issues when GUT is used as add-on).

Here is the list of errors of that type:

> Unable to open file: res://.godot/imported/play.png-5c90e88e8136487a183a099d67a7de24.ctex.
  Failed loading resource: res://.godot/imported/play.png-5c90e88e8136487a183a099d67a7de24.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/gut/gui/play.png. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/arrow.png-2b5b2d838b5b3467cf300ac2da1630d9.ctex.
  Failed loading resource: res://.godot/imported/arrow.png-2b5b2d838b5b3467cf300ac2da1630d9.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/gut/gui/arrow.png. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:283 - res://addons/gut/gui/RunAtCursor.tscn:35 - Parse Error: 
  Failed loading resource: res://addons/gut/gui/RunAtCursor.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  Unable to open file: res://.godot/imported/play.png-5c90e88e8136487a183a099d67a7de24.ctex.
  Failed loading resource: res://.godot/imported/play.png-5c90e88e8136487a183a099d67a7de24.ctex. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://addons/gut/gui/play.png. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/gut/gui/OutputText.gd:277 - Parse Error: Identifier "GutUtils" not declared in the current scope.
  scene/resources/resource_format_text.cpp:283 - res://addons/gut/gui/GutBottomPanel.tscn:50 - Parse Error: 
  Failed loading resource: res://addons/gut/gui/GutBottomPanel.tscn. Make sure resources have been imported by opening the project in the editor at least once.

Then a few ones I'm not sure if related:
> scene/resources/packed_scene.cpp:92 - Condition "nc == 0" is true. Returning: nullptr
  editor/editor_plugin.cpp:80 - Parameter "p_control" is null.
  res://addons/gut/gut_plugin.gd:11 - Invalid set index 'shortcut_in_tooltip' (on base: 'null instance') with value of type 'bool'.

Then a warning probably unrelated:
> editor/editor_node.cpp:3320 - Addon 'res://addons/plugin_refresher/plugin.cfg' failed to load. No directory found. Removing from enabled plugins.

Then unicode errors but those are unrelated and already handled in https://github.com/bitwes/Gut/issues/479

Finally a few last errors, probably unrelated:

> res://scratch/demo_extends_issue.gd:45 - Parse Error: "InnerClasses" is a variable but does not contain a type.
  res://scratch/demo_extends_issue.gd:47 - Parse Error: "InnerClasses" is a variable but does not contain a type.
  res://scratch/demo_extends_issue.gd:55 - Parse Error: "InnerClasses" is a variable but does not contain a type.
  res://scratch/demo_extends_issue.gd:57 - Parse Error: "InnerClasses" is a variable but does not contain a type.
  res://scratch/get_parent_class.gd:29 - Parse Error: "InnerClasses" is a variable but does not contain a type.
  res://test/samples/test_readme_examples.gd:352 - Parse Error: Function "end_test()" not found in base self.
