### ISSUE TITLE
Is it possible to fail on internal debugger errors?

### ISSUE THREAD

**Issue by 3ter** [bitwes/Gut#362]
In the debugger I can produce the error
```sh
resume: Resumed function 'my_func()' after yield, but class instance is gone. At script: res://my_script.gd:1337
  <C++ Error>   Method failed. Returning: Variant()
  <C++ Source>  modules/gdscript/gdscript_function.cpp:1802 @ resume()
```
but unfortunately `gut` doesn't yet react to it.

As mentioned in https://github.com/bitwes/Gut/issues/134#issuecomment-568230538 there doesn't seem to be a `get_error()` as a counterpart to `push_error()` (I searched for the very same thing). But as the issue has been closed, am I missing some config option I have to switch on to make it possible to fail on debugger errors?

**Comment by bitwes** [comment]
There is no way to detect these through Gut and likely never will be a way
due to how they handle errors in Godot.  There's no exception handling in
gdscript.

The good news is that error is most likely ignorable.  I have some tests
that will generate that error and it's caused by a yield happening in a
test, then the test finishes but the yielded function is still running.
The objects in the test all get released and there is nothing for the
yielded function to go back to.

It's possible to structure your tests to avoid this, but in most cases that
doesn't do anything except avoid the error and slow your tests down.

**Comment by 3ter** [comment]
Thanks for clearing it up @bitwes !

In my case I (misguidedly) had both a `on_my_signal()` listening function and a `yield(other_node, my_signal)` in a script, whose instance could be freed while the `yield` was still waiting.

My "solution" in this case was to add a signal to the script, that is emitted, when the listening function has been called. This way there was no _resuming_ when `my_signal` was emitted again, though the first thread was still running.
It's not really a good solution I presume because the thread most probably won't ever be reaped by the garbage collector...
