### ISSUE TITLE
Improve viewing results at a glance

### ISSUE THREAD

**Issue by TheDuckCow** [bitwes/Gut#363]
The idea here is to make it easy to quickly see which files / tests failed in the UI, without having to scroll through and squint at the console text. I sometimes work on a small monitor, and with the right-side settings bar not being collapsable, I can get pretty [heavy wordwrapping](https://user-images.githubusercontent.com/2958461/171193623-c0258a47-3327-4046-b9d6-7b43fdead246.png) that makes it hard to read tests outputs at a glance. Even with a wider screen, you still have to focus to follow the indention to see where failures are. To be clear, I'm not saying that should change, it's a console output afterall, but I would think it would be helpful to have a way to more quickly glance at what went wrong. Some aspects of this request could be similar or related to https://github.com/bitwes/Gut/issues/340, but I think they are complementary:

- The request here is more to do with creating additional interface hierarchy to _complement_ the detailed console output
- #340 could partially improve this request if the test filenames and test names themselves were color highlighted, but I still have to scroll to through a window with "all the detail" to see only the summary.
- If an interface is created around quick viewing which tests failed, it could tie in to the way you jump into those specific files, versus make the console out somehow a clickable experience.

The above description is intentionally vague about the precise user experience as I think it could be accomplished in a number of ways, some more subtle and simple, but some ideas:

- Simplest: Hover over or click the `Passing ## | Failing ##` sections to see just a dropdown or window that shows which test files+test names failed (or passed, if you hover over that one); maybe this is a modal popup since some people could have a huge number of entries. No interaction other than listing the names, though this popup could tie into #340.
- Hierarchy dropdown navigation of the tests themselves. I don't [love this experience](https://github.com/AlexDarigan/WAT/blob/main/images/gui.png) (this doesn't show "results", pretend it does), but there is some nugget of usefulness perhaps. It would also enable easy reruns of specific tests/files right from the panel, without having to jump in and open the specific test file and place your cursor to get the quick "Current: run" button (a feature, btw, I absolutely love)
- Most complex: Introduction of a tab system, split into "Results", "Console", "Settings" (you're typically only looking at one of these at once anyways, right?). "Results" or perhaps "Summary" here would be more of an interface wrapped around the raw console/internal structure. Consider an analogy of a structured json file where all fields and subfields start off in a collapsed state so you can view at a high level quickly and expand where you want. This also lends itself to future interactively without having to mess with the console output (I'd hope the console output in Godot stays exactly the same to my command prompt/terminal console out, so I can confidently use GUT with or without a UI with the same experience).

Sorry if I missed any similar proposals, I did a quick look and didn't find any.

**Comment by bitwes** [comment]
I love all of this.  I've been pondering improvements for the panel ever
since I introduced it.

My first concern was making tests easy to run, the next was tackling the
output.  #340 was my first quick idea, but I think a more user friendly
interface is needed.  I really like the tabbed idea.  And since GUT has an
xml (and undocumented JSON) export, this would map very well to a list of
tests that could be used interactively in a lot of ways.

Thanks for the feedback!

**Comment by bitwes** [comment]
@TheDuckCow I think I did all the stuff we talked about.  I'd be interested in feedback if you want to try it out.

**Comment by TheDuckCow** [comment]
Thanks a bunch, it's looking great! I figured showing was better than telling especially with "UX reveals", so here's a video for you:
https://www.youtube.com/watch?v=rply6c2g2M8

After finishing the recording of the video, I think I'd update my thoughts on the tabbed UI experience to be: More often than not, I'm looking at one of the 3 views vs another, and it would be nice to click on one of them to switch that to be the active view (instead of right now, where I have to click to console tab to show that, then click the Tree view to unshow that). Minor thing that maybe not everyone would agree with, and I understand the point of the current setup, using that to drive visibility of the feature.

**Comment by bitwes** [comment]
That video feedback was great!  I've been making some changes that haven't yet been merged.

The x/y feedback was nice, and I agree.  I chose that format because that is how the Runner displays the total in the title bar (Failures 0/10).  I've changed it up so it now says "X passed" or "X of Y passed" if any did not pass.  I think this relays the most information because tests could be failing, pending or risky (currently means they did not assert but may be expanded to include warnings and/or errors).  I've made similar changes to the summary and Runner display for consistency.

I've found that the two sets of expand/collapse buttons are more useful when you include passing tests, and have a large amount of tests (GUT currently has 41 scripts, 1100+ tests, and 1600+ asserts).  Many of those "scripts" inner-classes which are indented under the main script.  Being able to collapse everything, then expand a single script fully has been pretty convenient.  They do seem a bit redundant when there aren't a lot of tests being displayed.

The "include passing" button takes effect on the next run because `TreeItem` nodes do not have a visible property, which is disappointing.  Including/excluding passing tests means the tree must be rebuilt (or do a bunch of gymnastics to add/remove everything in the right spots).  I might change it so it reloads the file when you click it.

I've made it so the panel toggles are saved when you run tests.  They are all visible at first, but it will remember your choices across launches.

One thing that isn't obvious in your video is that when you click a node in the tree, it goes to that line in the test script.  So I added a toggle that will make Godot show the Script Editor when a tree item is clicked.  I've also made some changes to the output panel so that it will also scroll closest line related to the clicked item (your mileage will vary with log level).  This makes the output panel a lot more useful since you can use the tree instead of scrolling around.  The output panel is also getting a search bar.

Thanks again for the feedback, it has been very useful.  I'll let you know when the new changes have been merged so you can try them out.

**Comment by TheDuckCow** [comment]
This all sounds fantastic, and looking forward to tying it out when ready!On Jun 19, 2022 4:24 PM, Butch Wesley ***@***.***> wrote:
That video feedback was great!  I've been making some changes that haven't yet been merged.
The x/y feedback was nice, and I agree.  I chose that format because that is how the Runner displays the total in the title bar (Failures 0/10).  I've changed it up so it now says "X passed" or "X of Y passed" if any did not pass.  I think this relays the most information because tests could be failing, pending or risky (currently means they did not assert but may be expanded to include warnings and/or errors).  I've made similar changes to the summary and Runner display for consistency.
I've found that the two sets of expand/collapse buttons are more useful when you include passing tests, and have a large amount of tests (GUT currently has 41 scripts, 1100+ tests, and 1600+ asserts).  Many of those "scripts" inner-classes which are indented under the main script.  Being able to collapse everything, then expand a single script fully has been pretty convenient.  They do seem a bit redundant when there aren't a lot of tests being displayed.
The "include passing" button takes effect on the next run because TreeItem nodes do not have a visible property, which is disappointing.  Including/excluding passing tests means the tree must be rebuilt (or do a bunch of gymnastics to add/remove everything in the right spots).  I might change it so it reloads the file when you click it.
I've made it so the panel toggles are saved when you run tests.  They are all visible at first, but it will remember your choices across launches.
One thing that isn't obvious in your video is that when you click a node in the tree, it goes to that line in the test script.  So I added a toggle that will make Godot show the Script Editor when a tree item is clicked.  I've also made some changes to the output panel so that it will also scroll closest line related to the clicked item (your mileage will vary with log level).  This makes the output panel a lot more useful since you can use the tree instead of scrolling around.  The output panel is also getting a search bar.
Thanks again for the feedback, it has been very useful.  I'll let you know when the new changes have been merged so you can try them out.

**Comment by bitwes** [comment]
New changes have been merged.  Barring any issues I think this will suffice for a first stab.

**Comment by TheDuckCow** [comment]
Just tried it out - looking good, thanks for flipping around the pass/failed count logic, more intuitive now I think. Orphan count is nice too.

Only sort of edge case not sure if that summary view wordwraps at all now that I play with it. Minor to me, but for longer error messages is nice to be able to read it all.

<img width="1119" alt="Screen Shot 2022-06-26 at 5 37 47 PM" src="https://user-images.githubusercontent.com/2958461/175840696-1f216c87-05a3-4ef3-a22c-b32cb028830b.png">

**Comment by bitwes** [comment]
I think everything here has been implemented and released in 7.4.0.  Thanks for your help.
