### ISSUE TITLE
InputSender action_down("ui_select")

### ISSUE THREAD

**Issue by markeel** [bitwes/Gut#391]
I was trying to stimulate the press of a control (a simple button) using the InputSender "action_down" method.  As far as I can tell I've set it up correctly and when I send either a "mouse_left_button_down" or a "key_down(KEY_SPACE)" it does trigger the control.  But the "action_down('ui_select')" did not.

Is this because it was a built in control and not something being overridden?  If that is a known limitation it should be put in the Wiki/documentation for InputSender.

It is also possible I am not using action_down correctly, but I'm doing what I see in the documentation.

**Comment by bitwes** [comment]
I'm not sure it will work that way.  I didn't test sending input to bultin
controls.  Can you provide some sample code?

**Comment by markeel** [comment]
Sure here is a test project I was using to understand what GUT allows me to do.
[guttest.zip](https://github.com/bitwes/Gut/files/9328647/guttest.zip)

**Comment by bitwes** [comment]
Thanks for the test project, that really helped.  It looks like it should work, especially since sending `space` does work.  This _might_ be a bug in Godot.  I will update the documentation.

Pro-tip, you can skip one `yield` per test by putting a trailing `wait` or `wait_frames` at the end of your string of input:
```
_sender.mouse_left_button_down(mouse_pos)\
	.wait(0.1)\
	.mouse_left_button_up(mouse_pos)\
	.wait_frames(10)
yield(_sender, 'idle')
```

In looking at your code I think having a `click` function on the `InputSender` that would move the mouse to the center of a passed in object and then does a mouse down/up would be helpful so I'm adding that in.  Thanks for the inspiration.

**Comment by bitwes** [comment]
@markeel `ui_select` is not the right action for a button.  `ui_accept` works as expected.
