### ISSUE TITLE
Question: how do I "simulate" physics collisions between nodes in a scene?

### ISSUE THREAD

**Issue by microBob** [bitwes/Gut#418]
I would like to test a function on a node that runs based on the number of items it is colliding with.

I have a test scene with several nodes which I have loaded, instantiated, and added as a child node to the root scene. However, when I check for collisions I don't see any. From my understanding, GUT doesn't actually run scenes so physics interactions aren't computed. 

How can I test physics interactions with GUT?

I hope this is the right place to post questions like this. 

Thanks!

**Comment by bitwes** [comment]
This is a fine place to ask questions.  You will want to look into adding `yield` calls to your tests.  You have to `yield` for a time or to a signal or something, to let the engine process a few frames so that your collisions and other actions have a chance to play out.  

Take a look at the Yielding wiki page and let me know if you have any more questions.  https://github.com/bitwes/Gut/wiki/Yielding

**Comment by microBob** [comment]
Ah, that did the trick. Thank you for the quick reply!
