### ISSUE TITLE
awaiter.gd:59 @ wait_for_signal(): Signal '...' is already connected and awaiter.gd:41 @ _signal_callback(): Attempt to disconnect

### ISSUE THREAD

**Issue by theludovyc** [bitwes/Gut#518]
Hello 😊 

I working on that plugin https://github.com/rakugoteam/Rakugo-Dialogue-System

And when we ran "all tests" we have thoses errors

![image](https://github.com/bitwes/Gut/assets/7337158/a1634267-0c38-436d-b2a6-59b97732fb7b)

One by one, we have no errors. Or it is really rare.

Did we do something wrong when we wrote the tests ?

You can found them in Test/TestExecuter or Test/TestParser (https://github.com/rakugoteam/Rakugo-Dialogue-System/tree/main/Test)

We aslo create a class that extends GutTest to help us write tests more easier https://github.com/rakugoteam/Rakugo-Dialogue-System/blob/main/Test/RakugoTest.gd

**Comment by bitwes** [comment]
This looks to be a bug in GUT.  I created #525 to describe the specific bug in the code.  The good news is that you can ignore these errors until GUT is fixed or you implement the workaround described below.  Everything should work as expected with these errors.

I think this is being caused by using autoloads in your tests (it is bad practice generally).  In your case, I think the problem has to do with this:
```
func watch_rakugo_signals():
	watch_signals(Rakugo)
```
I don't see `Rakugo` defined in `RakugoTest.gd` so I'm guessing it is an autoload.  When writing tests you should be creating an instance of your object for each test to avoid any state changes that might leak from one test to another.  At the very least you should be creating a new instance per test script.

I think this is causing errors because the `awaiter` isn't disconnecting from signals when they are not fired.  Since you are using a "global", each time you wait on a signal from `Rakugo` there is a chance that signal has already been connected...I think.  It starts to get really messy when you use an autoload with `wait_for_signal`.  GUT should be able to handle this though, as it might be necessary in some edge cases.

**Comment by bitwes** [comment]
Fix implemented
