### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by RicardoQLG** [bitwes/Gut#537]
I have created a simple script to calculate current progress in percent, in the test I was distracted and returned an int instead of a float and the test result is a strange value

Production code
```GDScript
func handle() -> void:
	var size: float = _boardRepository.getSize()
	var progress: float = _boardRepository.getProgress()
	if (progress == 0):
		_textField.text = "0%"
		return
	_textField.text = str(progress / size * 100) + "%"
```

Test code
```GDScript
func test_should_update_text_with_correct_progress():
	stub(BoardRepository, "getSize").to_return(200)
	stub(BoardRepository, "getProgress").to_return(100)
	sut.handle()
	assert_eq(textField.text, "50%")
```

Result
![image](https://github.com/bitwes/Gut/assets/581306/ec5a1f01-e3d2-4917-981e-705618e8488a)

I fixed my test and now it works correctly, but I discussed it with my friend and he thinks this is a GUT error

**Comment by bitwes** [comment]
In your test, Gut is comparing two strings, so there couldn't be a floating
point calculation error.  The error was in the code.

**Comment by RicardoQLG** [comment]
The code is not the problem.
If I change from int to float the test passes

**Comment by bitwes** [comment]
`assert_eq(textField.text, "50%")` is comparing two strings, there is no calculation or conversion that is happening in GUT that would cause the values to change like that.  The values also have "%" in them, which no number will ever have, so it's clear that it is comparing the two string values that it was given.  In your example, the value of `textField.text` was "4632...2%", which means whatever populated `textField.text` is where the problem is.

Maybe you are stating that the call to `stub` is causing the error, but that wouldn't cause the problem either.  I don't see where the percent is being calculated, but I think it's somewhere in `sut.handle`.  Since you've stubbed the functions to return`int` values, your calculation isn't happening correctly and the `textField` is getting the wrong value.  To fix this, you must have cast the values to float in `sut.handle` or you changed the stubs to be floats (200.0, 100.0) and then it worked.  That is to be expected.  Dividing ints by floats and vice versa will give weird results as Godot must cast those values to do the calculation.

You can see this in action with the following
``` gdscript
func test_stuff():
    assert_eq(100/200, .5, 'int division does not give expected result')
    assert_eq(100.0/200.0, .5, 'float division gives expected result')
```
Which results in
```
* test_stuff
    [WARNING]:  Warn:  Float/Int comparison.  Got INT but expected FLOAT
    [Failed]:  [0] expected to equal [0.5]:  
      at line 4
    [Passed]:  [0.5] expected to equal [0.5]:  
```
This is the behavior of the engine, and not GUT.
