### ISSUE TITLE
_ready() is not called automatically when running tests

### ISSUE THREAD

**Issue by levinzonr** [bitwes/Gut#561]
First of all, thank you very much for this great tool
I am beginner in Godot and wanted to clarify if this is expected behaviour,  I was not able to found anything related to my issue while searching through the documentation

My health scene has a @export var available to define a `MAX_HEALTH` number and it has a default value. During _ready() I do the assignment to the internal `health`

```
var health_scene: PackedScene = load("res://components/HealthComponent.tscn")

func test_health_depleated():
	var component = health_scene.instantiate() as HealthComponent
	assert_eq(200, component.health)
```

When running the test, I expected that the _ready() would be called and the test would pass, but this is not the case.  It works if I call _ready() manually before doing the assertions. Should I call _ready() for every scene participating in the test before doing any scenarios?

**Comment by bitwes** [comment]
Glad you're enjoying GUT.  In your test you are not adding the instantiated scene to the scene tree, so `_ready` isn't called.  You could just call `add_child(component)` in your test and that would fix it.  The issue here is that as you add more tests each health scene will stick around after your test and you'll have one for each test.  You could then call `component.free()` after you make your assertions and that would free the component.  That's boring though, so GUT has `add_child_autofree(...)` which will add the scene to the tree and free the scene at the end of the test.  Unlike `add_child`, `add_child_autofree` will return whatever is passed to it.  So your test should look like:

```gdscript
var health_scene: PackedScene = load("res://components/HealthComponent.tscn")

func test_health_depleated():
	var component = add_child_autofree(health_scene.instantiate()) as HealthComponent
	assert_eq(200, component.health)
```

**Comment by levinzonr** [comment]
I see, that worked and fixed my orphans warnings that I was also wondering about!
Thanks a lot for the quick answer and great explanation 🙂

**Comment by bitwes** [comment]
Glad that worked, I hadn't tried it with `as Whatever` at the end so I wasn't 100% sure it would work.  Couldn't see why it wouldn't, but didn't try it.

FYI, there's more info about orphans and auto_free here:  https://gut.readthedocs.io/en/latest/Memory-Management.html
