### ISSUE TITLE
GUT v9.2.0: Exit on Finished does not work where test fails with "[ERROR]: Could not find script matching '...'"

### ISSUE THREAD

**Issue by hsandt** [bitwes/Gut#568]
I work on a lowres game and the GUT window embedded in game is not really usable, so I just keep Exit on Finished checked. But when a test cannot be found and I have the error:

> [ERROR]: Could not find script matching '...'

the window just stays there.

![image](https://github.com/bitwes/Gut/assets/1067772/d1ffc926-9ae1-4bfe-bb53-1e00e7426a6a)

I must close it and read the proper error message in the editor GUT window instead (by the way font size is 30 by default, which was also too big, so I had to reduce it to 14 to get a look similar to GUT v9.0)

It probably needs at least one test to work?

Repro
0. Check Exit on Finished
1. Intentionally disable Test Directories to force test file miss
2. Open .gd with test in missed file
3. Manually run some test in that file using the GUT Play buttons (not Run All)

**Comment by bitwes** [comment]
I leave the window open on purpose.  My thought was that the case where no test was found was unique enough that it should be treated differently.  That may have been done before the panel existed.  We can probably close the window now, even when a test isn't found (especially since directories can now be toggled).  I may need to add something to the panel to make it clear that no tests were ran.

As for the window not being usable in low res games, could you make another issue and list your resolution settings?  There might be some ways to address this, possibly through a pre-run hook script.  Having that info in another issue would be helpful.

**Comment by bitwes** [comment]
Creating another issue to handle no tests found.  It also states that all tests passed when no tests are found which is very misleading.
