### ISSUE TITLE
mocking mouse drag

### ISSUE THREAD

**Issue by lagodw** [bitwes/Gut#580]
I've been trying to figure out how to mock a mouse click and drag but can't quite figure out how it's supposed to be done. Side note: all of the documentation that I saw seems to be around keys so would really benefit from some mouse examples.

What I'm trying to test is someone right clicking on node A, dragging the mouse to node B, then releasing. Based on my understanding the test should look something like this:

```
test_target_arrow():
	var nodeA_pos = nodeA.global_position
	var nodeB_pos = nodeB.global_position
	_sender.add_receiver(nodeA)
	_sender.mouse_set_position(nodeA_pos, nodeA_pos)\
	.wait_frames(1)\
	.mouse_right_button_down(nodeA_pos, nodeA_pos)\
	.hold_for(1)\
	.mouse_motion(nodeB_pos, nodeB_pos)
	# don't need mouse up?
	await _sender.idle
	assert_true(nodeB_was_targeted)
```

I've tried this and just about every other permutation of the mouse functions but can't get it to pass. An arrow does show so the initial click is working and there's a red crosshair on node B, which I assume is coming from the mouse motion. The problem is it's not triggering the area_entered signal in node B so nothing happens. I was able to fudge the outcome by just manually emitting the area_entered signal in the test but for some other tests I would prefer to be able to do it via mouse movement. 

I also notice that the arrow points the actual position of my curser instead of the set mouse positions even if I don't touch the mouse. Am I supposed to tell it to ignore my real mouse position somehow?

**Comment by bitwes** [comment]
The mouse is weird.  I was toying with some ideas and they snuck there way into `main` and I haven't finished them or documented them yet.  Here's some sample code for how I was able to drag a button.  IMPORTANT.  This uses `Input` as the receiver, not a node.  Make sure you [understand how this works for your test setup](https://gut.readthedocs.io/en/latest/Input-Sender.html#using-input-as-a-receiver) before moving forward.

```
class DraggableButton:
	extends Button

	var _mouse_down = false

	func _gui_input(event):
		super._gui_input(event)
		if(event is InputEventMouseButton):
			_mouse_down = event.pressed
		elif(event is InputEventMouseMotion and _mouse_down):
			position += event.relative

var _sender = InputSender.new(Input)
func test_drag_a_button():
	var btn = DraggableButton.new()
	btn.size = Vector2(100, 100)
	btn.position = Vector2(50, 50)
	add_child_autofree(btn)

	# click down on the button
	_sender.mouse_left_button_down(btn.position + Vector2(10, 10)).wait(.1)

	# move the button
	for i in range(10):
		await _sender.mouse_relative_motion(Vector2(10, 10)).wait(.1).idle

	# release the button
	await _sender\
		.mouse_left_button_up()\
		.wait('1f')\
		.idle

	# move mouse more after we let go, which should not move the button
	for i in range(10):
		await _sender.mouse_relative_motion(Vector2(10, 10)).wait(.1).idle
```
This uses `Input` instead of the Button because...mouse.  If you wanted to use the button instead of `Input`, it would be better to use btn.mouse_entered.emit() instead of trying to simulate the mouse actually entering the button.  This way you are testing how you handle the events which is easier to reproduce than fighting with the mouse.

Let me know if this helps at all.  Input Mocking is an area that could use a lot of improvement, but It's unclear what direction it should take.  Your feedback will be helpful.

**Comment by lagodw** [comment]
As I wrote some more tests I was forced to rely on emitting area_entered signals but I actually found that works quite well and seems to be sufficient. I think you're right, I don't particularly care about what happens with the mouse I care about the events when it enters something so I'll probably just go that route instead. Thanks!
