### ISSUE TITLE
Question: How to skip Input tests which fail under --headless?

### ISSUE THREAD

**Issue by hatmix** [bitwes/Gut#598]
I am testing some detailed input handling and the tests work as expected from both the editor and the command-line without the --headless option. However, these fail when headless, probably for the reasons explained in comments in https://github.com/godotengine/godot/issues/73557 . 

Accepting this engine behavior, I'm now looking for: 
1. GUT's recommended way to skip tests--I didn't find anything in doc
2. A (straightforward) way to detect headless mode to trigger the skips

I found @russmatney's [comment](https://github.com/bitwes/Gut/issues/360#issuecomment-1191933031) in #360 useful for point 2, but was hoping in the meantime someone had found a better way.

TIA!

**Comment by hatmix** [comment]
Well, I was just impatient.  Below approach seems to work well enough and this could be just a documentation issue.

`
extends GutTest

var skip_script

func _init():
    if DisplayServer.get_name() == "headless":
        skip_script = "Skip Input tests when running headless"
`

**Comment by bitwes** [comment]
Unfortunately, I think GUT only looks to see if the var exists, not the value.  Which means you have to comment out all that code if you want to run those tests.

Adding a check to see if it has a value and only skipping the. Would be a solution, but a more concrete structure would be better.

One approach might be to put all your input tests in a different folder and make another gut config to use for headless which does not include that folder.  You can specify the gut_config file to use in the command line.

**Comment by hatmix** [comment]
https://github.com/bitwes/Gut/blob/a6272501efc069fd075cf9c20f27f00c07cb112d/addons/gut/gut.gd#L706 appears to be the only check.  I can also use the separate gut_config approach, thanks!

**Comment by bitwes** [comment]
My original idea with `var skip_script` was for temporarily skipping scripts (initially those that were not yet fully converted to Godot 4).  It was a quick hack I threw together.  I chose a variable so that it could seen easily at the top of the script.  Using it to conditionally skip scripts is not in the spirit of the variable.  It also requires two steps, declaring it and then setting it.

I never really liked how "magic" it was.  "Oh, I just declare a variable and then something different happens?...ok".  I probably shouldn't have documented its existence, heh.

I think a more formal solution for conditionally skipping scripts would be to create a virtual `should_skip_script()` method in `GutTest`.  You can then override this method in your test script to conditionally skip a script.
* Your implementation should return `true` or a string to skip the script.
* If a string is returned then it will be used in the message that GUT prints when skipping the script.
* Return `false` to run the script.  Anything else will generate an error message but still run the script.
* `GutTest` should have an implementation that just returns false.
* After this is implemented the `var skip_script` approach should be deprecated and removed in the next release.
* When `should_skip_script` results in the script being run, it should not cause any orphans.
* Skipped scripts are included in the risky count (for a lack of any better place).

Additional benefits of this approach
* Having a method would allow you to clean up any orphans you might create in variable declarations that you would free in `after_all`.
* You can still put `should_skip_script` at the top of the script where it is more visible.
* Later we could add a `should_skip_test` that passes in the test name which would allow you to conditionally skip specific tests (this doesn't sound like a great idea, but maybe it is).

**Comment by hatmix** [comment]
If opting for a bit more design, I wonder whether there's one approach that can work for both complete scripts and for individual inner classes.

**Comment by bitwes** [comment]
We could add a should_skip_file which would skip the script and any inner classes, so no tests run in the entire file.

You could also make your own script class that extends GutTest that has should_skip_script implemented and extend that instead of GutTest to "auto skip" a script/inner.

**Comment by bitwes** [comment]
This has been implemented in `main`.  See `CHANGES.md` for info on `should_skip_script` virtual method.
