### ISSUE TITLE
Problem with  installing GUT plugin for Godot 4.2

### ISSUE THREAD

**Issue by SpiritIV** [bitwes/Gut#604]
# Versions
*(list all versions where you have replicated the bug)*
* Godot: 4.2
* GUT: GUT 9.2.1
* OS: Ubuntu 22.04 LTS

# The Bug

I got some strange bug with installing GUT plugin. After installing it from official AssetLib, I can't add it to scene like a node.

You can see that it is not a scene or a node

![Screenshot from 2024-05-06 15-03-56](https://github.com/bitwes/Gut/assets/52663388/6ad09233-7c9f-4ada-955e-ba011fbab859)

# Steps To Reproduce

I tried to delete folder ".godot" and reinstall godot project.

**Comment by bitwes** [comment]
Did you activate the plugin in project settings, add-ons tab?  Also you don't need to make a scene anymore unless you want to run tests in an exported project.  You should see "Gut" in as a bottom tab, down by debug and output.

**Comment by SpiritIV** [comment]
Yes, I activated it in setting (checked "Enable" field).

**Comment by SpiritIV** [comment]
> Did you activate the plugin in project settings, add-ons tab? Also you don't need to make a scene anymore unless you want to run tests in an exported project. You should see "Gut" in as a bottom tab, down by debug and output.

I would like to implement tests during the start of project than I need a Gut node (

**Comment by bitwes** [comment]
The new name for that node is GutControl.  

https://gut.readthedocs.io/en/latest/Running-On-Devices.html

**Comment by bitwes** [comment]
I noticed you are using Add Node, you should be using the "instantiate child scene" button:
<img width="36" alt="image" src="https://github.com/bitwes/Gut/assets/1156520/1e6ae9c1-6f69-4626-bd0c-3df2cdb47281">

**Comment by SpiritIV** [comment]
Thank you for your comments! It works =)

**Comment by SpiritIV** [comment]
What does it mean?
![Uploading Screenshot from 2024-05-15 12-23-42.png…]()

**Comment by bitwes** [comment]
Based on the screenshot it looks like you attached a script to the `GutControl` node instead of the `UnitTests` node.  The error message is telling you that a script has the line `extends Node2D` but is attached to a `Control` node.  You should not be attaching scripts to the `GutControl` node, replacing the script on it will break it.

Can I ask why you are trying to get tests to run when the game is launched?  It's much easier/faster to develop your tests/game using the Gut Panel (see screenshot below).  Running tests through a scene is usually not needed until much later.

![image](https://github.com/bitwes/Gut/assets/1156520/688ca136-d0aa-4b18-817d-149e8208591d)

**Comment by SpiritIV** [comment]
I tried to implement it to my product crew and run automatic during the start. It will be easier to implement scene with tests but not to teach my teammates to use GUT.

**Comment by bitwes** [comment]
Gotcha.  Were you able to get it working?

**Comment by SpiritIV** [comment]
I'm on the way) Try to run it

**Comment by SpiritIV** [comment]
It works! I added scene with tests before game's start.
Thank you for your answer and support =)
