### ISSUE TITLE
Assert for Assertions

### ISSUE THREAD

**Issue by gabahulk** [bitwes/Gut#627]
# Versions
What versions of Godot do you want to use this feature in?
Godot 4.2

# The Feature

It would be nice if GUT could see if an `assert` is catching an error.
I don't know if this is possible now, but I didn't find it in the documentation.

**Comment by gabahulk** [comment]
I could see assertions for `push_error` and `push_warning` as well.

**Comment by bitwes** [comment]
This isn't possible from within GUT or Godot in general.  Godot does not provide any way to detect if an error has occurred. The best one can do is check the output.  From the command line, you could redirect the output and scrape it, but you wouldn't be able to mark any tests as failing due to an error.    

I know that they are firmly against introducing any form of exception handling, so I do not expect this to ever be added. If you could detect an error, you could implement similar behavior to exception handling...to some degree.
