### ISSUE TITLE
New method for float equality

### ISSUE THREAD

**Issue by hbergren** [bitwes/Gut#64]
When attempting to use `assert_eq(float1, float2)`, I get an error message like:

` FAILED:  [91.733333] expected to equal [91.733333]`

Now, I know that floats are never exactly equal, but I would like some way to see if they are more or less equal.

My suggestion is either:
1) A new method called `assert_floats_eq( )` specifically for floats, with a a call signature of `(got, expected, plus_or_minus, message)` where `plus_or_minus` is the acceptable error
2) Add an optional `plus_or_minus` parameter to the standard `assert_eq()`

For now, I can workaround this using an `assert_between` in each of my tests, but I would really like an `assert_approximately_eq` or equivalent.

**Comment by cmfcmf** [comment]
Hi @hbergren,
did you try to push the branch directly to this repository? That won't work, because only @bitwes has permissions to push to this repository directly. You most likely need to fork this repository using the `Fork` button above, then push your branch to your fork, and then create the PR from your fork to this repository. This is also described here: https://guides.github.com/activities/forking/

**Comment by hbergren** [comment]
Hi @cmfcmf ,

Thanks for the quick reply. I'll give that a try a little later. My current WIP PR doesn't yet meet all the requirements listed in the Contribution Guidelines.
