### ISSUE TITLE
Asserting properties

### ISSUE THREAD

**Issue by bitwes** [bitwes/Gut#70]
I haven't started using the "public" class variables that came along with 3.0 so I'm not sure right now how it would work...but asserting that these properties work or exist should be good.

For example you can just reference `.position` on something instead of using `get_position` or `set_position`.  I believe these still go through accessors but I haven't made any of these.  In my game I'm keeping with using get/set on my own objects to keep everything consistent.

If anyone has experience with these or any ideas I'd like to hear them.  It doesn't seem like it would be too hard but I'm too preoccupied right now to look into it.

**Comment by bitwes** [comment]
Looked into it a little.  This is done with the `setget` reserved word.  I wasn't able to find any way to detect these local variables.  I couldn't find 
* any flags on methods that indicated they were accessors
* anything that indicated which properties used `setget`
* the names of the methods that come after `setget`
I checked `get_property_list`, `get_meta_list` and `get_method_list` for any useful information.

My thought at this point is to create something that would work similarly to `assert_accessors`.  It would everything that it does but it would also `double` the object and get/set the value by directly referencing the variable name and `assert` that the accessors were called.

**Comment by short-story-long** [comment]
Hej, I'd like to look into this. before working on the actual pull request I'd like to double check the requirements.
example:
`class SomeClass`
  `var property = null setget set_property, get_property`
  `var attribute = null`

for the given example the new assert function should pass for "property" and fail for "attribute" because attribute is not using the setget keyword.

The setget keyword also allows the developer to only specify setter or getter function. so I'll keep that in mind as well.

**Comment by bitwes** [comment]
Correct.  

If the metadata for `setget` still does not exist (see below) then I think it would work like this:
```
var SomeClass = load('res://scripts/some_class.gd')
assert_setget(SomeClass, 'property', null, 5)
```
Under the covers it would do something like:
```
func assert_setget(base_class, prop_name, default_value, new_value):
  var inst = partial_double(base_class).new()
  assert_get_set_methods(inst, prop_name, default_value, new_value)
  
  # --- somehow dynamically do ---
  var temp = inst.<prop_name>
  inst.<prop_name> = new_value
  assert_called(inst, 'set_<prop_name>')
  assert_called(inst, 'get_<prop_name>')
```

Finding the metadata:
I haven't done any more research in this, there is a chance that they have added to the meta data for scripts and this information is now there.  I have a script that has examples of how to get metadata for scripts, scenes, instances, functions etc. This script might be helpful in tracking down where the metadata that indicates if a property has `setget` on it and what the methods are called.

https://github.com/bitwes/Gut/blob/master/scratch/get_info.gd

**Comment by short-story-long** [comment]
Awesome. Thanks for the further info's.

Checking if the given methods were actually called when a property is accessed is a good approach, I think. In this case we make sure not only the keyword setget exists but the methods named after it are the ones that should be accessed. so we can find cnp mistakes like this one:
`var property = 0 setget set_property, get_property`
`var another_property = 0 setget set_property, get_property`

As for the scope of the new assert I would like to keep it simple. Only checking if the given methods are called. And technically gdscript allows developers to freely name the methods. so my proposal will be something like:
`assert_setget_called(<type>, <name property>, <name setter>, <name getter>)`

I can provide a wrapper function though that combines the `assert_accessors` and `assert_setget_called` tests. so developers are more flexible to choose whatever suits their current situation. under the covers your proposed `assert_setget` would work like this:
```
func assert_setget(base_class, prop_name, default_value, new_value):
   # arrange
   ...
   # action
   assert_accessors(base_class, prop_name, default_value, new_value)
   assert_setget_called(base_class, prop_name, setter_name, getter_name)
   
   # check result
   if nothing failed:
      _pass(success_msg)
   else:
      _fail(error_msg)
```

I'm not sure what you mean with this: "[...] Maybe script and scene instances (this would be easier to use but makes doing the underlying double harder)." => give an object as input instead of base_class parameter?

**Comment by bitwes** [comment]
I like the modular approach, good idea.  I'd be ok with this parameter setup:
```
func assert_setget(base_class, prop_name, default_value, new_value, setter=null, getter=null):
func assert_setget_called(thing, prop_name, setter=null, getter=null):
```
If the setter and/or getter are null then it will assume `get_<prop_name>` and `set_<prop_name>`.  90% of the time this will be the naming convention so let's save everyone some time in writing the tests.

In regards to your last question:  If you pass an instance to `assert_setget_called`(`assert_accessors` only takes an instance, not a base class) then when you go to make your double to spy on the set and get methods, you will have to infer the base class to create the double.  It's possible, just an extra step.  (PS I don't know if that clears anything up, I had to reread it a couple times before it made sense and I wrote it.)

**Comment by short-story-long** [comment]
Cool, thanks for the feedback.
`Assert_accessors `assumes `set_<prop_name>` and `get_<prop_name>` as method names. therefore we will not need the fifth and sixth parameter. And as you mentioned, this naming convention is good practice so I want to encourage it for the wrapper as well.

As for the first input parameter the wrapper will be generous to the developer. So they can throw in an instance or a resource (script or packed scene). The method will try to make sense out of it.

Guess I'm good to go from here on. Everything else we can discuss once I made the pull request, I think.
