### ISSUE TITLE
Exporting project no longer runs tests

### ISSUE THREAD

**Issue by mashumafi** [bitwes/Gut#73]
I made a simple project with examples. Test run fine in editor and the popup is shown for my exported game. The problem is that no tests are detected. Nothing gets run and I am able to preload the test scripts but they still not detected by the popup.

**Comment by bitwes** [comment]
I think there is a flag (or was) to not export scripts as binary or something of that flavor.  This might help.  I was able to get tests to run on an iPhone at one point but I don't know if that still works.  This has been in the back of my head for awhile but haven't got around to figuring out how to get around it.

I believe it is because it has to parse the tests but when it does it doesn't find anything to test.

What platform were you exporting for?

**Comment by mashumafi** [comment]
I am using version 3.0.2 and I tested on windows + Linux/x11 exports.

**Comment by bitwes** [comment]
I'll toy around with this and see if I can't figure out what is going on.  I think it would be nice to be able to run tests on an exported game but not totally necessary.  Your tests shouldn't get deployed but it is nice to be able to put out a test build and run the tests on multiple platforms w/o having to install the editor.

**Comment by bitwes** [comment]
Here's what I've found:

The test scripts aren't run b/c on an export the `.gd` scripts are compiled into `.gdc` files.  A `.gd..remap` file is also created for each `.gd` script.  This is a `ConfigFile` that points to the `.gdc` file.  I assume this is how godot finds the new scripts.

We cannot change Gut to just follow this chain and load the scripts b/c you cannot get a list of Inner Test Classes by inspecting either the script object or the instance of the script.  There is a `script/source` property on a script object but it is null after being exported.  I can't find the names of any Inner Classes in `get_method_list`, `get_property_list`, or `get_meta_list` on either the script or an instance (`script = load('res://somescript.gd')` and instance = `script = load('res://somescript.gd').new()`)

As a workaround I went hunting for an old 2.x setting that allowed you to export scripts as text but it doesn't seem to exist anymore.  One forum post put out the idea to manually remove all the `.gd.remap` and `.gdc` files and put the .gd scripts back but that doesn't seem like a viable solution when working with phones.  It'd be too tedious, especially with android where it's only a click to get your program running on the phone.  https://godotengine.org/qa/30675/can-gd-be-exported-as-text-not-binary-in-3-x

The only solution I can think of is to make a list of scripts and Inner Test Classes when Gut runs.  This list would include ALL the scripts and Inner Test Classes that it configured to find, regardless of which scripts/tests it actually runs due to other settings that might limit a run to a single script or Inner Class etc.  

When running locally (on mac at least) I think you can write to `res://`.  I know that you can't on phones.  But if we can write this file to `res://` it should get exported as long as your export settings are set to export files of that type ("Filters to export non-resource files", btw, I did try adding '*.gd' to this list and it didn't work).  We then setup Gut to look for .gd files first, if it doesn't find any then it will look for that file.  If it finds .gd files then it will index all the scripts and Inner Classes and then make the file.

When using the list, Gut should honor the `.gd.remap` -> `.gdc` chain.  For each script that is listed in the generated file it should look for the `.gd.remap` file and open whatever file is listed in there.  I'm assuming this is in place for some valid reason and doing this should future proof Gut.

For testing purposes we'll need `.gd.remap` and `.gdc` files in the `parsing_and_loading_samples` directory.  We will also need to verify that all tests pass when exported.

This is the best approach I've been able to conjure up.  I'm open to suggestions if anyone has one.  Thanks to mashumafi for creating the issue and taking an initial stab at it.  Even though I couldn't use his code due to the Inner Test Class issue, it helped in clarifying what was going on and helped identify other issues.

**Comment by Xrayez** [comment]
Exporting scripts as text worked in 2.1, as well as encrypting them.

In 3.1, I managed to resurrect it being lost in a rewrite mess at the time it seems:
godotengine/godot#24582

The `Script Export Mode` can be turned to `Text` so that scripts are exported as `.gd`, not `.gdc`, so this might help to solve the issue.

**Comment by bitwes** [comment]
Dammit that is great news!  "Dammit" b/c I just started working on a fix for it and it had far reaching implications.

**Comment by bitwes** [comment]
Implemented in 6.7.0 for 3.0.  Broke in 3.1 right now but the exporting as text works.  Will create another issue to fix in 3.1 or just use the 3.1 issues page in the wiki to track it.
