### ISSUE TITLE
Option to include Sub Folders for Tests

### ISSUE THREAD

**Issue by paulhocker** [bitwes/Gut#83]
First, great utility. Amazed to find that this was already made by someone, so thank you for building this.

I understand in the Docs that there is a limit to 6 folders, and that additional folder can be added. However, in my projects I tend to have all tests included under one folder, sometimes very nested. It would be nice (great) to be able to toggle a setting to let it include every sub directory under that folder.

Appreciate your consideration, and if I have time I will likely submit a PR to do this. ;)

**Comment by bitwes** [comment]
Thanks.  There's a PR out there now to include subfolders.  U haven't had a
chance to look at it that much.  Right now the hold up is whether I want an
option or to just do it.  I think I want an option.

Im commenting about it here first because I didn't want you to do the same
work someone else already did.

The existing PR should get worked in soon.  In the meantime you can call
`add_directory` to add more manually.

**Comment by paulhocker** [comment]
Thanks for telling me about that, I did not even think to see if there was a pull request. Looking forward to it.

**Comment by adadgio** [comment]
Closed but the feature is not here ? I don't get it! Truly a great tool, but seems strange not to run tests in subfolders by default.
