### ISSUE TITLE
Doubling a Scene child in a packed scene

### ISSUE THREAD

**Issue by Nolic0321** [bitwes/Gut#92]
Not sure where the best place is to ask this but wanted to know how/if this is the best way to test a Scene with instanced child scenes.

My example

Player (Scene)
|
| - PathRunner (Child Scene)

Within my "Player" code I reference $PathRunner and just wanted to know if I can double/stub the PathRunner scene methods and have them return controlled values...like this as an exampe

````
var player= preload("res://player.tscn")
var PATHRUNNER = "res://pathrunner.tscn)"

func before_each():
	var testPlayer = player.instance()
        var testRunner = double(PATHRUNNER).instance()
        stub(PATHRUNNER, "some_method").to_return(true)
        ...
````

Now if the player scene calls ````$PathRunner.some_method()```` can I expect "true" to be returned from the stubbed instance?

**Comment by bitwes** [comment]
This should work and on the surface seems like a perfectly normal way of doing things.  I can't tell from the limited code but if you are trying to test that something happens when you get `true` from a "PathRunner" then this would be the way to unit test that.

Your sample code is missing two steps but you got the right idea.
1.  You have to use `double_scene` instead of `double` for scenes.  It's on my list to make `double` smart enough for both but I haven't got around to it.
1.  You will have to set `player`'s PathRunner `$PathRunner` to the doubled scene instance.

```
var player= preload("res://player.tscn")
var PATHRUNNER = "res://pathrunner.tscn)"

func before_each():
	var testPlayer = player.instance()
        var testRunner = double_scene(PATHRUNNER).instance()
        stub(PATHRUNNER, "some_method").to_return(true)
        testPlayer.set_path_runner(testRunner) # assuming you have/make an accessor for path runner
        ...
```

Let me know if that works.  Doubling/stubbing is a bit cumbersome still so any feedback is helpful.

**Comment by bitwes** [comment]
I'm going to close this, but if it didn't work or you have more questions feel free to re-open.
