### ISSUE TITLE
asserting remote procedural calls are being called

### ISSUE THREAD

**Issue by AlexAndDraw** [bitwes/Gut#97]
[Relevant Gists](https://gist.github.com/AlexAndDraw/2305cba406c460777e99079c2302cb82/)

Firstly it should be noted that I am using the new MultiplayerAPI in 3.1 (Alpha 3), so some nodes have many of their tree methods replaced with a custom handler. However since both join and host server are passing, this doesn't seem to be an issue.

I have a client that yields on its multiplayer emitting "connected_to_server", at this point it sends an rpc to call "register_player" on the server. I currently do not understand how to do this correctly in GUT. 

It currently fails on assert_called(server, "register_player")

**Comment by schweigert** [comment]
In several test environments, such as in web development, it is necessary to have the real environment for running the tests. I believe that because it is a native method, it is difficult to perform mocks and asserts of the multiplayer API.

**Comment by Xrayez** [comment]
Does it actually register a player? Have you tried to increase the delta time in `gut.simulate()`? It might take more time because of the lag, even locally.

**Comment by AlexAndDraw** [comment]
> Does it actually register a player? Have you tried to increase the delta time in `gut.simulate()`? It might take more time because of the lag, even locally.

I was probably unclear. I'm sure it doesn't call register_player because I'm confident that the issue is somewhere previous to that.

> In several test environments, such as in web development, it is necessary to have the real environment for running the tests. I believe that because it is a native method, it is difficult to perform mocks and asserts of the multiplayer API.

Seems you might be right on this, _host_server() is being called:

```
func _host_server() -> void:
	_server = NetworkedMultiplayerENet.new()
	_server.create_server(_PORT, _MAX_PLAYERS)
	multiplayer.set_network_peer(_server)
```

In this test, host_server is called BUT set_network_peer hasn't, which results in a null peer (hence no messages)

```
func test_connectivity():
	var server = double("res://Server/Server.gd").new()
	watch_signals(server)
	watch_signals(server.multiplayer)
	add_child(server)
	gut.simulate(server, 20, 0.1)
	assert_signal_emitted(server, "ready")
	assert_called(server, "_ready")
	assert_called(server, "_host_server")
        # Complaint about double instance being required but is native (DI  a double maybe?)
	assert_called(server.multiplayer, "set_network_peer") 
	assert_true(server._server == null, "Peer is null") # Peer shouldn't be nul
``` 

We're failing to assert multiplayer calls (because it isn't doubled) and our ._server is returning null. I'm currently messing around with trying to inject a custom multiplayer double (but as of yet no luck).

**Comment by AlexAndDraw** [comment]
Alright, so I'm pretty confident I understand the issue now. 

I was wanting to use assert_called(method) which requires doubles but doubles over-ride the base methods with empty implementations for you to stub them. The reason why I never had a peer connected was because host_server wasn't actually doing anything (because gut is calling the empty unstubbed method of the double). 

With that in mind, a lot of my tests require easier to stub methods if using doubles, or stateful tests if just using things straight. This [gist](https://gist.github.com/AlexAndDraw/25159e65778f739e20ea9daa4db960af) is an example of a number of connectivity methods passing properly.

(Not a particularly good test script itself though).

**Comment by bitwes** [comment]
Are you good on this now?  It looks like you got it.  I looked over the gists a little, and have some input below.  I would say normally you would "double" the client or the server to test the other one.  Or have the other one running locally that you can connect to.  This is where fuzzy line between unit and integration tests come in.  Unit tests shouldn't any external dependencies and Integration tests test multiple components together.  It's all just semantics.  This looks like you might benefit more from integration tests for some of this behavior.  


On the `internet example.gd` gist I had a couple of notes that might help.
* You are using `simulate` and then a `yield`.  I just wanted to make sure you knew that the 3 simulate calls will run synchronously, one right after the other.  I'm not 100% sure what's going on, but it kinda looks like that might make a difference to you.
* `assert_true(y._client != null, "")` might be better written as `assert_ne(y._client, null)`.  It'll give you a little friendlier message when it fails.
* Also wanted to point out that `gut` has some yield helpers that might be useful.  There is `yield_to` and `yield_for`.  `yield_to` might be useful for you, since it will allow the test to continue if a signal was not fired.  For example, you can change
```
yield(y.multiplayer, "connected_to_server")
```
to
```
yield(yield_to(y.multiplayer, "connected_to_server", 10), YIELD)
```
and then Gut will take care of emitting a signal when `connected_to_server` is emitted or `10` seconds elapse, whichever comes first.  That way if your signal is never emitted the test does not hang forever.

If you  still have a specific question, go ahead and ask.  If not, please close.  Thanks.
